#ifndef ERROR_H
#define ERROR_H

#include "Debug.h"

enum ServerErrors 
{
  //Generic Errors
  FAILURE = -1,
  SUCCESS = 0,
  ALLOCATION_ERR,
  NULL_POINTER,
  THREAD_CREATION_ERR,

  // Socket Errors
  SOCKET_CREATION_ERR = 10,
  SOCKET_BIND_ERR,
  SOCKET_LISTEN_ERR,
  SOCKET_ACCEPT_ERR,
  SOCKET_OPT_SET_ERR,
  INVALID_SOCKET_ERR,
  
  // Client Messaging Errors
  MAX_CLIENTS_CONNECTED_ERR = 20,
  INVALID_BUFFER_SIZE,
  INVALID_MSG_SIZE,
  INVALID_MSG_ID
};

#endif
